version: '3.9'

services:
  delivery-service:
    build: .
    env_file:
      - .env.dev
    volumes:
      - './src:/var/www/delivery-service/src'
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: mongo:4.4.4-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=delivery-service

  db_manager:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    depends_on:
      - db
